# Generated by Django 5.1.6 on 2025-02-12 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_usuario_senha_alter_usuario_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
    ]
