# Generated by Django 5.1.6 on 2025-02-14 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_usuario_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
