# Generated by Django 5.1.6 on 2025-02-14 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_remove_usuario_nome_usuario_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_name',
        ),
    ]
