"""empty message

Revision ID: 0280e4d17314
Revises: 3f052dcf21dc
Create Date: 2025-01-16 16:26:52.762348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0280e4d17314'
down_revision = '3f052dcf21dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ingredientes', sa.Text(), nullable=False),
    sa.Column('modo_preparo', sa.Text(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receitas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receitas_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('alimentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alimentos_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alimentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alimentos_usuario_id'))

    with op.batch_alter_table('receitas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receitas_usuario_id'))

    op.drop_table('receitas')
    # ### end Alembic commands ###
