"""empty message

Revision ID: 5fc30fab2d97
Revises: 374bc9d89b18
Create Date: 2025-01-10 19:05:47.450183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fc30fab2d97'
down_revision = '374bc9d89b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genero', sa.Enum('Masculino', 'Feminino', name='gender_enum'), nullable=False))
        batch_op.add_column(sa.Column('data_nascimento', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('senha', sa.String(length=200), nullable=False))
        batch_op.drop_column('birthdate')
        batch_op.drop_column('gender')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('gender', mysql.ENUM('Masculino', 'Feminino'), nullable=False))
        batch_op.add_column(sa.Column('birthdate', sa.DATE(), nullable=False))
        batch_op.drop_column('senha')
        batch_op.drop_column('data_nascimento')
        batch_op.drop_column('genero')

    # ### end Alembic commands ###
