# Generated by Django 5.1.6 on 2025-02-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receitas',
        ),
    ]
